version: '2'


services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="Ento333"
    networks:
      - lan_wpdb
    volumes:
      - vol_wpdb:/var/lib/mysql

  wordpress_ento:
    depends_on:
      - db
    image: wordpress:4.7.2-php7.1-fpm-alpine
    restart: always
    working_dir: /var/www/html/ento
    environment:
      - WORDPRESS_TABLE_PREFIX=ento_wp
      - WORDPRESS_DB_PASSWORD="Ento333"
      - WORDPRESS_DB_HOST=db:3306
    volumes:
      - ./www/html/ento:/var/www/html/ento:rw
    networks:
      - lan_wpdb
      - lan_server

  wordpress_kawale:
    depends_on:
      - db
    image: wordpress:4.7.2-php7.1-fpm-alpine
    restart: always
    working_dir: /var/www/html/kawale
    environment:
      - WORDPRESS_TABLE_PREFIX=kawale_wp
      - WORDPRESS_DB_PASSWORD="Ento333"
      - WORDPRESS_DB_HOST=db:3306
    volumes:
      - ./www/html/kawale:/var/www/html/kawale:rw
    networks:
      - lan_wpdb
      - lan_server



        
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    #   domainname: 'kawale.org'
    #   hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.kawale.org'
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        nginx['listen_port'] = 80   
    #ports:
    #  - '80:80'
    #  - '443:443'
    #  - '22:22'
    volumes:
      - ./gitlab:/etc/gitlab
      - vol_gitlab_logs:/var/log/gitlab
      - vol_gitlab_contents:/var/opt/gitlab
    networks:
      - lan_server




  server:
    restart: always
    depends_on:
      - wordpress_kawale
      - wordpress_ento
    #  - gitlab
    #  -letsencrypt
    image: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - .nginx.conf:/etc/nginx/nginx.conf.d:ro
      - ./www/html:/var/www/html:ro
      - vol_letsencrypt_certs:/etc/letsencrypt
      - vol_letsencrypt_www:/var/lib/letsencrypt/www
    ports: 
      - 80:80
      - 443:443
    networks:
      - lan_server


  temp_certs:
    build: 
      context: ./dockerfile/letsencrypt
      dockerfile: Dockerfile
    image: temp_certs
    command: /bin/true
    volumes:
      - vol_letsencrypt_certs:/etc/letsencrypt
      - vol_letsencrypt_www:/var/lib/letsencrypt/www

  letsencrypt:
    image:  quay.io/letsencrypt/letsencrypt:latest
    command: certonly --noninteractive --agree-tos --verbose --config /etc/letsencrypt/cli.ini
    volumes:
      - ./letsencrypt/cli.ini:/etc/letsencrypt/cli.ini
      - vol_letsencrypt_certs:/etc/letsencrypt
      - vol_letsencrypt_www:/var/lib/letsencrypt/www
    networks:
      lan_server:
        aliases:
          - letsencrypt
    environment:
      - TERM=xterm


volumes:
  vol_wpdb:
    driver: local
  vol_wp:
    driver: local
  vol_gitlab_logs:
    driver: local
  vol_gitlab_contents:
    driver: local
  vol_letsencrypt_certs:
    driver: local
  vol_letsencrypt_www:
    driver: local

networks:
  lan_wpdb:
  lan_server:
