version: '2'


services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="Ento333"
    networks:
      - lan_wpdb
    volumes:
      - vol_wpdb:/var/lib/mysql

  wordpress_ento:
    depends_on:
      - db
    image: wordpress:4.7.2-php7.1-fpm-alpine
    restart: always
    working_dir: /var/www/html/ento
    environment:
      - WORDPRESS_TABLE_PREFIX=ento_wp
      - WORDPRESS_DB_PASSWORD="Ento333"
      - WORDPRESS_DB_HOST=db:3306
    volumes:
      - ./www/html/ento:/var/www/html/ento:rw
    networks:
      - lan_wpdb
      - lan_server

  wordpress_kawale:
    depends_on:
      - db
    image: wordpress:4.7.2-php7.1-fpm-alpine
    restart: always
    working_dir: /var/www/html/kawale
    environment:
      - WORDPRESS_TABLE_PREFIX=kawale_wp
      - WORDPRESS_DB_PASSWORD="Ento333"
      - WORDPRESS_DB_HOST=db:3306
    volumes:
      - ./www/html/kawale:/var/www/html/kawale:rw
    networks:
      - lan_wpdb
      - lan_server

#  gitlab:
#    depends_on:
#      - server
#    image: 'gitlab/gitlab-ce:latest'
#    restart: always
#    hostname: 'gitlab.localhost'
#    environment:     GITLAB_OMNIBUS_CONFIG: |
#      external_url 'http://gitlab.localhost'
#    ports:
#      - '80:80'
#      - '443:443'
#      - '22:22'
#    volumes:
#      - ./gitlab/config:/etc/gitlab
#      - '/srv/gitlab/logs:/var/log/gitlab'
#      - '/srv/gitlab/data:/var/opt/gitlab'
#    networks:
#      - lan_server


  server:
    depends_on:
      - wordpress_kawale
      - wordpress_ento
    image: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - .nginx.conf:/etc/nginx/nginx.conf.d:ro
      - ./www/html:/var/www/html:ro
    ports : 
      - 8080:80
    networks:
      - lan_server

#  php:
#    image: php:fpm
#    networks:
#      - lan_wpdb
#    volumes:
#      - ./www:/var/www


volumes:
  vol_wpdb:
    driver: local
  vol_wp:
    driver: local
  vol_gitlab:
    driver: local

networks:
  lan_wpdb:
  lan_server:
